org: animl
app: animl
service: animl-frontend

plugins:
  - serverless-finch

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: us-west-2
  # profile: animl
  environment:
    REGION: ${self:provider.region}
    STAGE: ${self:provider.stage}

custom:
  client:
    bucketName: animl-frontend-${self:provider.stage}
    distributionFolder: build
    indexDocument: index.html
    errorDocument: index.html

resources:
  Resources:
    CloudfrontDistributionAnimlSite:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
            - DomainName: animl-frontend-${opt:stage, self:provider.stage, 'dev'}.s3-website-us-west-2.amazonaws.com
              Id: animl-frontend-${self:provider.stage}
              CustomOriginConfig:
                OriginProtocolPolicy: http-only

          Enabled: 'true'
          Comment: "Animl frontend - ${opt:stage, self:provider.stage, 'dev'} site"
          Aliases:
            - animl-${opt:stage, self:provider.stage, 'dev'}.camera
            - www.animl-${opt:stage, self:provider.stage, 'dev'}.camera
            - "*.animl-${opt:stage, self:provider.stage, 'dev'}.camera"
          DefaultCacheBehavior:
            AllowedMethods:
              - GET
              - HEAD
            TargetOriginId: animl-frontend-${self:provider.stage}
            MinTTL: 86400 # 1 day - perhaps adjust for staging?
            MaxTTL: 31536000 # 1 year
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # CachingOptimized
            ViewerProtocolPolicy: 'redirect-to-https'
          HttpVersion: http2
          ViewerCertificate:
            AcmCertificateArn: arn:aws:acm:us-east-1:830244800171:certificate/f7771033-aaad-4989-a570-726f570a7e5b
            MinimumProtocolVersion: 'TLSv1.2_2021'
            SslSupportMethod: 'sni-only'
