org: animl
app: animl
service: animl-frontend

plugins:
  - serverless-finch

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: us-west-2
  profile: animl
  environment:
    REGION: ${self:provider.region}
    STAGE: ${self:provider.stage}

custom:
  client:
    bucketName: animl-frontend-${self:provider.stage}
    distributionFolder: build
    indexDocument: index.html
    errorDocument: index.html

params:
  dev:
    domain: animl-dev.camera
    certificate: arn:aws:acm:us-east-1:830244800171:certificate/f7771033-aaad-4989-a570-726f570a7e5b
  staging:
    domain: animl-staging.camera
    certificate: arn:aws:acm:us-east-1:830244800171:certificate/63178d9d-ddb1-4412-95eb-4454bc2d9be4
  prod:
    domain: animl.camera
    certificate: arn:aws:acm:us-east-1:830244800171:certificate/6184d1f6-6df7-40b9-8598-64aa123d72a1

resources:
  Resources:
    CloudfrontDistributionAnimlSite:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
            - DomainName: animl-frontend-${self:provider.stage}.s3-website-us-west-2.amazonaws.com
              Id: animl-frontend-${self:provider.stage}
              CustomOriginConfig:
                OriginProtocolPolicy: http-only

          Enabled: 'true'
          Comment: 'Animl frontend - ${self:provider.stage} site'
          Aliases:
            - ${param:domain}
            - www.${param:domain}
            - '*.${param:domain}'
          DefaultCacheBehavior:
            AllowedMethods:
              - GET
              - HEAD
            TargetOriginId: animl-frontend-${self:provider.stage}
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # CachingOptimized
            ViewerProtocolPolicy: 'redirect-to-https'
          HttpVersion: http2
          ViewerCertificate:
            AcmCertificateArn: ${param:certificate}
            MinimumProtocolVersion: 'TLSv1.2_2021'
            SslSupportMethod: 'sni-only'
